### ISSUE TITLE
Zet formulier elementen in een form

### ISSUE THREAD

**Issue by joostf** [Mokerstier/Mokerstier.github.io#1]
https://github.com/Mokerstier/Mokerstier.github.io/blob/40f78f6d21b19ae491219bb4f9dc2530b8f07c84/index.html#L23-L24

**Comment by Mokerstier** [comment]
moet ik hier misschien een button van maken?
en dan een addEventlistener toevoegen?

ik heb nu een css truukje als de checkbox wordt aangevinkt komt het zoekformulier te voorschijn.

**Comment by Mokerstier** [comment]
heb er twee buttons van gemaakt met addEventListener

https://github.com/Mokerstier/Mokerstier.github.io/blob/c9d1188a6cc1e4d359a02bea60e775d002a6bdd6/index.html#L32-L34


javascript:
function showForm(){
    zoekForm.classList.add('showform');
    zoekForm.classList.toggle('index');
    sectionDirect.classList.add('hide');
    sectionArticle.classList.add('hide');
    terugButton.classList.add('showterug');
    terugButton.classList.remove('hide');
}
function hideForm(){
    zoekForm.classList.remove('showform');
    zoekForm.classList.toggle('index');
    sectionDirect.classList.remove('hide');
    sectionArticle.classList.remove('hide');
    terugButton.classList.remove('showterug');
}
