### ISSUE TITLE
Heading levels kloppen niet

### ISSUE THREAD

**Issue by joostf** [Mokerstier/Mokerstier.github.io#2]
https://github.com/Mokerstier/Mokerstier.github.io/blob/40f78f6d21b19ae491219bb4f9dc2530b8f07c84/index.html#L25-L28

**Comment by Mokerstier** [comment]
https://github.com/Mokerstier/Mokerstier.github.io/blob/22cc1174e3a1eba0cc2157868ca3a63a6a155a91/index.html#L27-L29

nu wel!
