### ISSUE TITLE
Handle javascript events niet in HTML

### ISSUE THREAD

**Issue by joostf** [Mokerstier/Mokerstier.github.io#7]
https://github.com/Mokerstier/Mokerstier.github.io/blob/40f78f6d21b19ae491219bb4f9dc2530b8f07c84/resultaten.html#L28

**Comment by Mokerstier** [comment]
https://github.com/Mokerstier/Mokerstier.github.io/blob/22cc1174e3a1eba0cc2157868ca3a63a6a155a91/java/script.js#L35-L37

gedaan
